#!/usr/bin/env bash
set -euo pipefail

helm install \
  cert-manager oci://quay.io/jetstack/charts/cert-manager \
  --version v1.19.1 \
  --namespace cert-manager \
  --create-namespace \
  --set crds.enabled=true

echo "cert-manager installed successfully!"