#!/usr/bin/env bash
set -euo pipefail

source .env

# Validate required files exist
if [[ ! -f ".env" ]]; then
    echo "Error: .env file not found in current directory. "
    exit 1
fi

# WARNING: dont change "namespace=opentelemetry-operator-system" as it is used in the 'instrumentation' CRD defined in values.yaml

echo "Installing OpenTelemetry Kube Stack Helm Chart..."

kubectl create namespace opentelemetry-operator-system || echo "WARNING Namespace 'opentelemetry-operator-system' already exists, continuing..."

kubectl create secret generic grafana-cloud-auth \
  --namespace opentelemetry-operator-system  \
  --from-literal=GRAFANA_CLOUD_INSTANCE_ID="$GRAFANA_CLOUD_INSTANCE_ID" \
  --from-literal=GRAFANA_CLOUD_OTLP_ENDPOINT="$GRAFANA_CLOUD_OTLP_ENDPOINT" \
  --from-literal=GRAFANA_CLOUD_API_KEY="$GRAFANA_CLOUD_API_KEY" || echo "WARNING Secret 'grafana-cloud-auth' already exists in namespace 'opentelemetry-operator-system', continuing..."

helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
helm repo update

# TODO customize these values as needed
export K8S_CLUSTER_NAME="my_k8s_cluster"
export DEPLOYMENT_ENVIRONMENT_NAME="staging"

# TODO shall we specify the version of the opentelemetry-kube-stack chart?

helm upgrade opentelemetry-stack opentelemetry/opentelemetry-kube-stack \
    --install \
    --namespace opentelemetry-operator-system \
    --set-string clusterName=$K8S_CLUSTER_NAME \
    --set-string instrumentation.resource.resourceAttributes.deployment\\.environment\\.name=$DEPLOYMENT_ENVIRONMENT_NAME \
    -f values.yaml

echo ""
echo "OpenTelemetry Kube Stack Helm Chart installation completed successfully!"
echo "Send OTLP to 'http://opentelemetry-stack-daemon-collector.opentelemetry-operator-system.svc.cluster.local:4318' (http/protobuff)"
echo "Or annotate your pods with: 'instrumentation.opentelemetry.io/inject-<<language>>: opentelemetry-operator-system/otel-instrumentation' to auto-instrument them."